/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as OurCarsRouteImport } from './routes/our-cars'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAboutRouteImport } from './routes/admin.about'
import { Route as AdminAccountRouteImport } from './routes/admin.account'
import { Route as AdminContactRouteImport } from './routes/admin.contact'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminFooterRouteImport } from './routes/admin.footer'
import { Route as AdminHeroRouteImport } from './routes/admin.hero'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminRoutesRouteImport } from './routes/admin.routes'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminVehicleRouteImport } from './routes/admin.vehicle'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const OurCarsRoute = OurCarsRouteImport.update({
  id: '/our-cars',
  path: '/our-cars',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAboutRoute = AdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFooterRoute = AdminFooterRouteImport.update({
  id: '/footer',
  path: '/footer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoutesRoute = AdminRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVehicleRoute = AdminVehicleRouteImport.update({
  id: '/vehicle',
  path: '/vehicle',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/our-cars': typeof OurCarsRoute
  '/routes': typeof RoutesRoute
  '/services': typeof ServicesRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/vehicle': typeof AdminVehicleRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/our-cars': typeof OurCarsRoute
  '/routes': typeof RoutesRoute
  '/services': typeof ServicesRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/vehicle': typeof AdminVehicleRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/our-cars': typeof OurCarsRoute
  '/routes': typeof RoutesRoute
  '/services': typeof ServicesRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/vehicle': typeof AdminVehicleRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/book'
    | '/contact'
    | '/our-cars'
    | '/routes'
    | '/services'
    | '/admin/about'
    | '/admin/account'
    | '/admin/contact'
    | '/admin/enquiries'
    | '/admin/footer'
    | '/admin/hero'
    | '/admin/media'
    | '/admin/routes'
    | '/admin/services'
    | '/admin/vehicle'
    | '/admin/'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/our-cars'
    | '/routes'
    | '/services'
    | '/admin/about'
    | '/admin/account'
    | '/admin/contact'
    | '/admin/enquiries'
    | '/admin/footer'
    | '/admin/hero'
    | '/admin/media'
    | '/admin/routes'
    | '/admin/services'
    | '/admin/vehicle'
    | '/admin'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/book'
    | '/contact'
    | '/our-cars'
    | '/routes'
    | '/services'
    | '/admin/about'
    | '/admin/account'
    | '/admin/contact'
    | '/admin/enquiries'
    | '/admin/footer'
    | '/admin/hero'
    | '/admin/media'
    | '/admin/routes'
    | '/admin/services'
    | '/admin/vehicle'
    | '/admin/'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  OurCarsRoute: typeof OurCarsRoute
  RoutesRoute: typeof RoutesRoute
  ServicesRoute: typeof ServicesRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-cars': {
      id: '/our-cars'
      path: '/our-cars'
      fullPath: '/our-cars'
      preLoaderRoute: typeof OurCarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/footer': {
      id: '/admin/footer'
      path: '/footer'
      fullPath: '/admin/footer'
      preLoaderRoute: typeof AdminFooterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/routes': {
      id: '/admin/routes'
      path: '/routes'
      fullPath: '/admin/routes'
      preLoaderRoute: typeof AdminRoutesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vehicle': {
      id: '/admin/vehicle'
      path: '/vehicle'
      fullPath: '/admin/vehicle'
      preLoaderRoute: typeof AdminVehicleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAboutRoute: typeof AdminAboutRoute
  AdminAccountRoute: typeof AdminAccountRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminFooterRoute: typeof AdminFooterRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminRoutesRoute: typeof AdminRoutesRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminVehicleRoute: typeof AdminVehicleRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAboutRoute: AdminAboutRoute,
  AdminAccountRoute: AdminAccountRoute,
  AdminContactRoute: AdminContactRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminFooterRoute: AdminFooterRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminRoutesRoute: AdminRoutesRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminVehicleRoute: AdminVehicleRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  OurCarsRoute: OurCarsRoute,
  RoutesRoute: RoutesRoute,
  ServicesRoute: ServicesRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
